"""empty message

Revision ID: 2f076816324d
Revises: dd633001cd1d
Create Date: 2025-03-28 20:54:30.465630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f076816324d'
down_revision = 'dd633001cd1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attraction_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attraction_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attraction_type_name'), ['name'], unique=True)

    op.create_table('park',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=35), nullable=True),
    sa.Column('abbreviation', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('park', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_park_abbreviation'), ['abbreviation'], unique=True)
        batch_op.create_index(batch_op.f('ix_park_name'), ['name'], unique=True)

    op.create_table('attraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.Column('attractiontype_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.ForeignKeyConstraint(['attractiontype_id'], ['attraction_type.id'], ),
    sa.ForeignKeyConstraint(['park_id'], ['park.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attraction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attraction_name'), ['name'], unique=True)

    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attraction_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attraction_id'], ['attraction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entry_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_timestamp'))

    op.drop_table('entry')
    with op.batch_alter_table('attraction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attraction_name'))

    op.drop_table('attraction')
    with op.batch_alter_table('park', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_park_name'))
        batch_op.drop_index(batch_op.f('ix_park_abbreviation'))

    op.drop_table('park')
    with op.batch_alter_table('attraction_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attraction_type_name'))

    op.drop_table('attraction_type')
    # ### end Alembic commands ###
